id: AE0485DBB
title: Toh_384-Glorious_King_of_Tantras_That_Resolves_All_Secrets-v1
type: translation
pechas:
- IB371B475
- I58F7E128
source_metadata:
  creationtool: 84000-translation-memory
  creationtoolversion: 1.0.0.0
  datatype: PlainText
  segtype: phrase
  adminlang: en
  srclang: bo
  o-tmf: TEI
  creationdate: '2018-03-27T17:55:30.044Z'
  creationid: dirk
  eft-text-id: UT22084-079-011
  xmlns-eft: http://read.84000.co/ns/1.0
  title: Toh_384-Glorious_King_of_Tantras_That_Resolves_All_Secrets-v1
alignment_to_base:
  IB371B475/A000: D25A
  I58F7E128/241D: D25A
